# Generated by Django 5.1 on 2024-11-21 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "category_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("category_name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "nit",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("industry", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("creation_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("department_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OpportunityStage",
            fields=[
                (
                    "stage_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("stage_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductService",
            fields=[
                (
                    "product_service_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("product_service_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "role_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("role_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "contact_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("position", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("last_interaction_date", models.DateField(blank=True, null=True)),
                (
                    "nit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pgadmin.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "contract_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("contract_number", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("monthly_value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "nit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pgadmin.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryCertificate",
            fields=[
                (
                    "certificate_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("delivery_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "contract_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pgadmin.contract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "equipment_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("inventory_code", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                (
                    "category_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pgadmin.category",
                    ),
                ),
                (
                    "certificate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pgadmin.deliverycertificate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "interaction_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("interaction_date", models.DateField(auto_now_add=True)),
                (
                    "interaction_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "contact_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pgadmin.contact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "opportunity_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("opportunity_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("estimated_close_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="open", max_length=20)),
                (
                    "success_probability",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "contact_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pgadmin.contact",
                    ),
                ),
                (
                    "nit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pgadmin.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "nit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pgadmin.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_date", models.DateField(auto_now_add=True)),
                (
                    "contact_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pgadmin.contact",
                    ),
                ),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pgadmin.department",
                    ),
                ),
            ],
            options={
                "unique_together": {("contact_id", "department_id")},
            },
        ),
        migrations.CreateModel(
            name="OpportunityStageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "opportunity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pgadmin.opportunity",
                    ),
                ),
                (
                    "stage_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pgadmin.opportunitystage",
                    ),
                ),
            ],
            options={
                "unique_together": {("opportunity_id", "stage_id")},
            },
        ),
        migrations.CreateModel(
            name="OpportunityProductService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "negotiated_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "opportunity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pgadmin.opportunity",
                    ),
                ),
                (
                    "product_service_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pgadmin.productservice",
                    ),
                ),
            ],
            options={
                "unique_together": {("opportunity_id", "product_service_id")},
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pgadmin.role"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pgadmin.useraccount",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "role_id")},
            },
        ),
    ]
